/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package tutoriales.liferay.servicebuilder.libro.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import tutoriales.liferay.servicebuilder.libro.model.Escritor;
import tutoriales.liferay.servicebuilder.libro.service.EscritorLocalService;
import tutoriales.liferay.servicebuilder.libro.service.persistence.EscritorPersistence;
import tutoriales.liferay.servicebuilder.libro.service.persistence.LibroPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the escritor local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link tutoriales.liferay.servicebuilder.libro.service.impl.EscritorLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tutoriales.liferay.servicebuilder.libro.service.impl.EscritorLocalServiceImpl
 * @see tutoriales.liferay.servicebuilder.libro.service.EscritorLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class EscritorLocalServiceBaseImpl extends BaseLocalServiceImpl
	implements EscritorLocalService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link tutoriales.liferay.servicebuilder.libro.service.EscritorLocalServiceUtil} to access the escritor local service.
	 */

	/**
	 * Adds the escritor to the database. Also notifies the appropriate model listeners.
	 *
	 * @param escritor the escritor
	 * @return the escritor that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Escritor addEscritor(Escritor escritor) {
		escritor.setNew(true);

		return escritorPersistence.update(escritor);
	}

	/**
	 * Creates a new escritor with the primary key. Does not add the escritor to the database.
	 *
	 * @param escritorId the primary key for the new escritor
	 * @return the new escritor
	 */
	@Override
	public Escritor createEscritor(long escritorId) {
		return escritorPersistence.create(escritorId);
	}

	/**
	 * Deletes the escritor with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param escritorId the primary key of the escritor
	 * @return the escritor that was removed
	 * @throws PortalException if a escritor with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Escritor deleteEscritor(long escritorId) throws PortalException {
		return escritorPersistence.remove(escritorId);
	}

	/**
	 * Deletes the escritor from the database. Also notifies the appropriate model listeners.
	 *
	 * @param escritor the escritor
	 * @return the escritor that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public Escritor deleteEscritor(Escritor escritor) {
		return escritorPersistence.remove(escritor);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(Escritor.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return escritorPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tutoriales.liferay.servicebuilder.libro.model.impl.EscritorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return escritorPersistence.findWithDynamicQuery(dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tutoriales.liferay.servicebuilder.libro.model.impl.EscritorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return escritorPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return escritorPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return escritorPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public Escritor fetchEscritor(long escritorId) {
		return escritorPersistence.fetchByPrimaryKey(escritorId);
	}

	/**
	 * Returns the escritor matching the UUID and group.
	 *
	 * @param uuid the escritor's UUID
	 * @param groupId the primary key of the group
	 * @return the matching escritor, or <code>null</code> if a matching escritor could not be found
	 */
	@Override
	public Escritor fetchEscritorByUuidAndGroupId(String uuid, long groupId) {
		return escritorPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the escritor with the primary key.
	 *
	 * @param escritorId the primary key of the escritor
	 * @return the escritor
	 * @throws PortalException if a escritor with the primary key could not be found
	 */
	@Override
	public Escritor getEscritor(long escritorId) throws PortalException {
		return escritorPersistence.findByPrimaryKey(escritorId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(escritorLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Escritor.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("escritorId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(escritorLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(Escritor.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("escritorId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(escritorLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(Escritor.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("escritorId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {
		final ExportActionableDynamicQuery exportActionableDynamicQuery = new ExportActionableDynamicQuery() {
				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary = portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(stagedModelType,
						modelAdditionCount);

					long modelDeletionCount = ExportImportHelperUtil.getModelDeletionCount(portletDataContext,
							stagedModelType);

					manifestSummary.addModelDeletionCount(stagedModelType,
						modelDeletionCount);

					return modelAdditionCount;
				}
			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(new ActionableDynamicQuery.AddCriteriaMethod() {
				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(dynamicQuery,
						"modifiedDate");
				}
			});

		exportActionableDynamicQuery.setCompanyId(portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(new ActionableDynamicQuery.PerformActionMethod<Escritor>() {
				@Override
				public void performAction(Escritor escritor)
					throws PortalException {
					StagedModelDataHandlerUtil.exportStagedModel(portletDataContext,
						escritor);
				}
			});
		exportActionableDynamicQuery.setStagedModelType(new StagedModelType(
				PortalUtil.getClassNameId(Escritor.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return escritorLocalService.deleteEscritor((Escritor)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return escritorPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the escritors matching the UUID and company.
	 *
	 * @param uuid the UUID of the escritors
	 * @param companyId the primary key of the company
	 * @return the matching escritors, or an empty list if no matches were found
	 */
	@Override
	public List<Escritor> getEscritorsByUuidAndCompanyId(String uuid,
		long companyId) {
		return escritorPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of escritors matching the UUID and company.
	 *
	 * @param uuid the UUID of the escritors
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of escritors
	 * @param end the upper bound of the range of escritors (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching escritors, or an empty list if no matches were found
	 */
	@Override
	public List<Escritor> getEscritorsByUuidAndCompanyId(String uuid,
		long companyId, int start, int end,
		OrderByComparator<Escritor> orderByComparator) {
		return escritorPersistence.findByUuid_C(uuid, companyId, start, end,
			orderByComparator);
	}

	/**
	 * Returns the escritor matching the UUID and group.
	 *
	 * @param uuid the escritor's UUID
	 * @param groupId the primary key of the group
	 * @return the matching escritor
	 * @throws PortalException if a matching escritor could not be found
	 */
	@Override
	public Escritor getEscritorByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {
		return escritorPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the escritors.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link tutoriales.liferay.servicebuilder.libro.model.impl.EscritorModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of escritors
	 * @param end the upper bound of the range of escritors (not inclusive)
	 * @return the range of escritors
	 */
	@Override
	public List<Escritor> getEscritors(int start, int end) {
		return escritorPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of escritors.
	 *
	 * @return the number of escritors
	 */
	@Override
	public int getEscritorsCount() {
		return escritorPersistence.countAll();
	}

	/**
	 * Updates the escritor in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param escritor the escritor
	 * @return the escritor that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public Escritor updateEscritor(Escritor escritor) {
		return escritorPersistence.update(escritor);
	}

	/**
	 */
	@Override
	public void addLibroEscritor(long libroId, long escritorId) {
		libroPersistence.addEscritor(libroId, escritorId);
	}

	/**
	 */
	@Override
	public void addLibroEscritor(long libroId, Escritor escritor) {
		libroPersistence.addEscritor(libroId, escritor);
	}

	/**
	 */
	@Override
	public void addLibroEscritors(long libroId, long[] escritorIds) {
		libroPersistence.addEscritors(libroId, escritorIds);
	}

	/**
	 */
	@Override
	public void addLibroEscritors(long libroId, List<Escritor> escritors) {
		libroPersistence.addEscritors(libroId, escritors);
	}

	/**
	 */
	@Override
	public void clearLibroEscritors(long libroId) {
		libroPersistence.clearEscritors(libroId);
	}

	/**
	 */
	@Override
	public void deleteLibroEscritor(long libroId, long escritorId) {
		libroPersistence.removeEscritor(libroId, escritorId);
	}

	/**
	 */
	@Override
	public void deleteLibroEscritor(long libroId, Escritor escritor) {
		libroPersistence.removeEscritor(libroId, escritor);
	}

	/**
	 */
	@Override
	public void deleteLibroEscritors(long libroId, long[] escritorIds) {
		libroPersistence.removeEscritors(libroId, escritorIds);
	}

	/**
	 */
	@Override
	public void deleteLibroEscritors(long libroId, List<Escritor> escritors) {
		libroPersistence.removeEscritors(libroId, escritors);
	}

	/**
	 * Returns the libroIds of the libros associated with the escritor.
	 *
	 * @param escritorId the escritorId of the escritor
	 * @return long[] the libroIds of libros associated with the escritor
	 */
	@Override
	public long[] getLibroPrimaryKeys(long escritorId) {
		return escritorPersistence.getLibroPrimaryKeys(escritorId);
	}

	/**
	 */
	@Override
	public List<Escritor> getLibroEscritors(long libroId) {
		return libroPersistence.getEscritors(libroId);
	}

	/**
	 */
	@Override
	public List<Escritor> getLibroEscritors(long libroId, int start, int end) {
		return libroPersistence.getEscritors(libroId, start, end);
	}

	/**
	 */
	@Override
	public List<Escritor> getLibroEscritors(long libroId, int start, int end,
		OrderByComparator<Escritor> orderByComparator) {
		return libroPersistence.getEscritors(libroId, start, end,
			orderByComparator);
	}

	/**
	 */
	@Override
	public int getLibroEscritorsCount(long libroId) {
		return libroPersistence.getEscritorsSize(libroId);
	}

	/**
	 */
	@Override
	public boolean hasLibroEscritor(long libroId, long escritorId) {
		return libroPersistence.containsEscritor(libroId, escritorId);
	}

	/**
	 */
	@Override
	public boolean hasLibroEscritors(long libroId) {
		return libroPersistence.containsEscritors(libroId);
	}

	/**
	 */
	@Override
	public void setLibroEscritors(long libroId, long[] escritorIds) {
		libroPersistence.setEscritors(libroId, escritorIds);
	}

	/**
	 * Returns the escritor local service.
	 *
	 * @return the escritor local service
	 */
	public EscritorLocalService getEscritorLocalService() {
		return escritorLocalService;
	}

	/**
	 * Sets the escritor local service.
	 *
	 * @param escritorLocalService the escritor local service
	 */
	public void setEscritorLocalService(
		EscritorLocalService escritorLocalService) {
		this.escritorLocalService = escritorLocalService;
	}

	/**
	 * Returns the escritor persistence.
	 *
	 * @return the escritor persistence
	 */
	public EscritorPersistence getEscritorPersistence() {
		return escritorPersistence;
	}

	/**
	 * Sets the escritor persistence.
	 *
	 * @param escritorPersistence the escritor persistence
	 */
	public void setEscritorPersistence(EscritorPersistence escritorPersistence) {
		this.escritorPersistence = escritorPersistence;
	}

	/**
	 * Returns the libro local service.
	 *
	 * @return the libro local service
	 */
	public tutoriales.liferay.servicebuilder.libro.service.LibroLocalService getLibroLocalService() {
		return libroLocalService;
	}

	/**
	 * Sets the libro local service.
	 *
	 * @param libroLocalService the libro local service
	 */
	public void setLibroLocalService(
		tutoriales.liferay.servicebuilder.libro.service.LibroLocalService libroLocalService) {
		this.libroLocalService = libroLocalService;
	}

	/**
	 * Returns the libro persistence.
	 *
	 * @return the libro persistence
	 */
	public LibroPersistence getLibroPersistence() {
		return libroPersistence;
	}

	/**
	 * Sets the libro persistence.
	 *
	 * @param libroPersistence the libro persistence
	 */
	public void setLibroPersistence(LibroPersistence libroPersistence) {
		this.libroPersistence = libroPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("tutoriales.liferay.servicebuilder.libro.model.Escritor",
			escritorLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"tutoriales.liferay.servicebuilder.libro.model.Escritor");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return EscritorLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return Escritor.class;
	}

	protected String getModelClassName() {
		return Escritor.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = escritorPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = EscritorLocalService.class)
	protected EscritorLocalService escritorLocalService;
	@BeanReference(type = EscritorPersistence.class)
	protected EscritorPersistence escritorPersistence;
	@BeanReference(type = tutoriales.liferay.servicebuilder.libro.service.LibroLocalService.class)
	protected tutoriales.liferay.servicebuilder.libro.service.LibroLocalService libroLocalService;
	@BeanReference(type = LibroPersistence.class)
	protected LibroPersistence libroPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}